# Generated by Django 3.2.12 on 2024-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240521_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metric2',
            field=models.CharField(default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='metric',
            field=models.CharField(default='na', max_length=2),
        ),
    ]
