# Generated by Django 3.2.12 on 2024-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240521_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metric2',
            field=models.CharField(default='na', max_length=2),
        ),
    ]
