# Generated by Django 3.2.12 on 2024-05-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_metric2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='none', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='metric2',
            field=models.CharField(default='na', max_length=2),
        ),
    ]
